title: Cat Baker's Blog
theme: jekyll-theme-hacker
author: Catherene Baker
email: catbak3r@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog will cover anything and everything under the sun. Why put a limit on curiosity?
# social links
github_username:  catbak3r
linkedin_username: Catherene Baker

show_excerpts: true # set to false to remove excerpts on the homepage
