title: Cat Baker's Blog
theme: jekyll-theme-cayman
author: Catherene Baker
email: catbak3r@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog will cover a wide variety of topics related to Information Security. Some topics will appear on the surface to be unrelated but once you read further you will understand. 
# social links
github_username:  catbak3r
linkedin_username: Catherene Baker

show_excerpts: true # set to false to remove excerpts on the homepage
